import { boolean, index, integer, pgTable, text, timestamp, unique } from 'drizzle-orm/pg-core'

export const user = pgTable('user', {
  id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(),
})
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const profiles = pgTable('profiles', { userId: text('userId').primaryKey(), username: text('username').notNull().unique(), displayName: text('displayName').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const friendRequests = pgTable('friend_requests', { id: text('id').primaryKey(), senderId: text('senderId').notNull(), recipientId: text('recipientId').notNull(), status: text('status').notNull().default('pending'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() }, (t) => [unique().on(t.senderId, t.recipientId), index('friend_requests_recipient_status_idx').on(t.recipientId, t.status)])
export const conversations = pgTable('conversations', { id: text('id').primaryKey(), userAId: text('userAId').notNull(), userBId: text('userBId').notNull(), status: text('status').notNull().default('active'), lastMessageSnippet: text('lastMessageSnippet'), lastMessageAt: timestamp('lastMessageAt'), createdAt: timestamp('createdAt').notNull().defaultNow() }, (t) => [unique().on(t.userAId, t.userBId)])
export const messages = pgTable('messages', { id: text('id').primaryKey(), conversationId: text('conversationId').notNull(), senderId: text('senderId').notNull(), body: text('body').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), deliveredAt: timestamp('deliveredAt'), readAt: timestamp('readAt') }, (t) => [index('messages_conversation_created_idx').on(t.conversationId, t.createdAt)])

export const federationDeployments = pgTable('federation_deployments', { id: text('id').primaryKey(), origin: text('origin').notNull().unique(), protocolVersion: text('protocolVersion').notNull().default('v1'), publicKey: text('publicKey'), lastManifestAt: timestamp('lastManifestAt'), status: text('status').notNull().default('active'), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const federationFriendships = pgTable('federation_friendships', { id: text('id').primaryKey(), localUserId: text('localUserId').notNull(), remoteDeploymentId: text('remoteDeploymentId').notNull(), remoteUserId: text('remoteUserId').notNull(), remoteUsername: text('remoteUsername').notNull(), status: text('status').notNull().default('active'), tokenHash: text('tokenHash').notNull(), tokenVersion: text('tokenVersion').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), acceptedAt: timestamp('acceptedAt'), revokedAt: timestamp('revokedAt') }, (t) => [unique().on(t.localUserId, t.remoteDeploymentId, t.remoteUserId)])
export const federationRequests = pgTable('federation_requests', { id: text('id').primaryKey(), senderUserId: text('senderUserId').notNull(), senderOrigin: text('senderOrigin').notNull(), senderUsername: text('senderUsername').notNull(), recipientUsername: text('recipientUsername').notNull(), nonceHash: text('nonceHash').notNull(), expiresAt: timestamp('expiresAt').notNull(), status: text('status').notNull().default('pending'), idempotencyKey: text('idempotencyKey').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() }, (t) => [index('federation_requests_recipient_idx').on(t.recipientUsername, t.status)])
export const federationInbox = pgTable('federation_inbox', { id: text('id').primaryKey(), remoteEventId: text('remoteEventId').notNull().unique(), friendshipId: text('friendshipId').notNull(), payloadHash: text('payloadHash').notNull(), acceptedAt: timestamp('acceptedAt').notNull().defaultNow() })
export const federationOutbox = pgTable('federation_outbox', { id: text('id').primaryKey(), friendshipId: text('friendshipId').notNull(), messageId: text('messageId').notNull(), remoteEndpoint: text('remoteEndpoint').notNull(), payloadHash: text('payloadHash').notNull(), status: text('status').notNull().default('queued'), attemptCount: integer('attemptCount').notNull().default(0), nextAttemptAt: timestamp('nextAttemptAt').notNull().defaultNow(), remoteAcknowledgement: text('remoteAcknowledgement'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() }, (t) => [index('federation_outbox_retry_idx').on(t.status, t.nextAttemptAt)])
export const pushSubscriptions = pgTable('push_subscriptions', { id: text('id').primaryKey(), userId: text('userId').notNull(), endpoint: text('endpoint').notNull().unique(), p256dh: text('p256dh').notNull(), auth: text('auth').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), lastUsedAt: timestamp('lastUsedAt') })

export const systemConfig = pgTable('system_config', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
})

export const schema = { user, session, account, verification, profiles, friendRequests, conversations, messages, federationDeployments, federationFriendships, federationRequests, federationInbox, federationOutbox, pushSubscriptions, systemConfig }
export type Schema = typeof schema
